# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz/question'),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz/answer'),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
